import { chromium, expect } from '@playwright/test';
import { existsSync, mkdirSync } from 'node:fs';

const url = process.env.EXPLORER_URL || 'http://127.0.0.1:8000';
const edge = 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
const browser = await chromium.launch({ headless: true, ...(existsSync(edge) ? { executablePath: edge } : {}) });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
mkdirSync('test-results', { recursive: true });
const file = path => `${url}/#file?${new URLSearchParams({ path })}`;
try {
  await page.goto(url);
  await expect(page.locator('.hero')).toBeVisible();
  await expect(page.locator('.project-card').filter({ hasText: 'ESP32 · TFLite Micro' })).toBeVisible();
  await expect(page.locator('.project-card').filter({ hasText: 'ESP32 · WASM / AOT' })).toBeVisible();
  await expect(page.locator('#sidebar [aria-current="page"]')).toHaveText('Visão geral');
  await page.screenshot({ path: 'test-results/overview-desktop.png', fullPage: true });
  await page.goto(file('ESP32/cnn_webassembly_esp32/report.csv'));
  await expect(page.locator('.metric').filter({ hasText: 'Inferência média' })).toBeVisible();
  await expect(page.locator('.line-chart')).toHaveCount(2);
  await expect(page.locator('#rows tr')).toHaveCount(50);
  await page.locator('#next').click();
  await expect(page.locator('#page-count')).toContainText('Página 2');
  await page.locator('#row-search').fill('A0001');
  await expect(page.locator('#row-count')).toHaveText('1 registros');
  await page.locator('#row-search').clear();
  await page.locator('#only-errors').check();
  await expect(page.locator('#rows .good')).toHaveCount(0);
  await page.locator('#only-errors').uncheck();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'test-results/report-desktop.png', fullPage: true });
  await page.goto(file('models/drowsiness/reports/12-inferencia-wasm.txt'));
  await expect(page.locator('.metric').filter({ hasText: 'Acurácia' })).toContainText('98,25');
  await expect(page.locator('.metric').filter({ hasText: 'Inválidos / empates' })).toContainText('5');
  const index = await (await page.request.get(`${url}/api/index`)).json();
  const memory = index.entries.find(e => /memoria/.test(e.path) && e.kind === 'report');
  await page.goto(file(memory.path));
  await expect(page.locator('.memory-bar')).toBeVisible();
  await page.goto(file('models/mobilenetv2_alpha035/reports/12-inferencia-wasm.txt'));
  await expect(page.locator('.rank-row')).toHaveCount(5);
  await page.goto(file('docs/00-visao-geral-arquitetura.pt-BR.md'));
  await expect(page.locator('#markdown')).toBeVisible();
  await page.getByRole('link', { name: 'Read in English', exact: true }).click();
  await expect(page.locator('#markdown')).toBeVisible();
  await expect(page).toHaveURL(/00-architecture-overview.md/);
  await page.screenshot({ path: 'test-results/document-desktop.png', fullPage: true });
  await page.goto(`${url}/#documents`);
  await page.locator('#language-filter').selectOption('all');
  await page.locator('#search').fill('README');
  await expect(page.locator('.file-row').first()).toBeVisible();
  await page.locator('#refresh').click();
  await expect(page.locator('#refresh')).toBeEnabled();
  expect((await page.request.get(`${url}/api/file?path=../README.md`)).status()).toBe(404);
  expect((await page.request.get(`${url}/config.json`)).status()).toBe(404);
  const download = await page.request.get(`${url}/api/file?path=README.md&download=1`);
  expect(download.headers()['content-disposition']).toContain('attachment');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(url);
  await expect(page.locator('.hero')).toBeVisible();
  await page.screenshot({ path: 'test-results/overview-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('#menu').click();
  await expect(page.locator('#menu')).toHaveAttribute('aria-expanded', 'true');
  await page.locator('#sidebar').getByRole('link', { name: 'Documentação', exact: true }).click();
  await expect(page.locator('#menu')).toHaveAttribute('aria-expanded', 'false');
  await page.goto(file('ESP32/cnn_webassembly_esp32/report.csv'));
  await expect(page.locator('.line-chart')).toHaveCount(2);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('#ui-language').click();
  await expect(page.locator('html')).toHaveAttribute('lang', 'en');
  await expect(page.locator('#refresh')).toContainText('Refresh index');
  await expect(page.locator('.metric').filter({ hasText: 'Average inference' })).toBeVisible();
  await expect(page.locator('#page-count')).toContainText('Page 1 of');
  await expect(page.locator('#row-search')).toHaveAttribute('placeholder', 'Filter records…');
  await expect(page.locator('.chart-title').first()).toContainText('Inference per sample');
  await page.locator('#row-search').fill('A0001');
  await expect(page.locator('#row-count')).toHaveText('1 records');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.reload();
  await expect(page.locator('.metric').filter({ hasText: 'Average inference' })).toBeVisible();
  await page.goto(`${url}/#documents`);
  await expect(page.locator('#language-filter')).toHaveValue('en');
  await expect(page.locator('#search')).toHaveAttribute('placeholder', 'Search documents, topics or paths…');
  await page.goto(file('docs/00-architecture-overview.md'));
  await expect(page.locator('#markdown')).toBeVisible();
  await expect(page.locator('.copy-code').first()).toHaveText('Copy');
  await page.locator('#ui-language').click();
  await expect(page).toHaveURL(/00-visao-geral-arquitetura.pt-BR.md/);
  await expect(page.locator('#markdown')).toBeVisible();
  await expect(page.locator('#refresh')).toContainText('Atualizar índice');
  await page.locator('#ui-language').click();
  await expect(page).toHaveURL(/00-architecture-overview.md/);
  await expect(page.locator('#markdown')).toBeVisible();
  await page.goto(url);
  await expect(page.locator('.hero h1')).toContainText('From model to device.');
  await page.screenshot({ path: 'test-results/overview-english-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'test-results/overview-english-desktop.png', fullPage: true });
  await page.locator('#ui-language').click();
  await expect(page.locator('.hero h1')).toContainText('Do modelo ao dispositivo.');
  expect(errors).toEqual([]);
  console.log('Browser checks passed: navigation, reports, filters, language, downloads, desktop and mobile.');
} finally {
  await browser.close();
}
