import { chromium, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';

const url = process.env.EXPLORER_URL || 'http://127.0.0.1:8013';
const browser = await chromium.launch({headless: true, executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
try {
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const before = await (await page.request.get(`${url}/api/consolidation`)).json();
  await page.goto(`${url}/#analysis`);
  await expect(page.locator('#consolidation-table tbody tr')).toHaveCount(50);
  await page.locator('#consolidation-next').click();
  await expect(page.locator('#consolidation-page')).toContainText('2 /');
  await page.locator('[data-filter="env"]').selectOption('esp32');
  await page.locator('[data-filter="search"]').fill('A0001.raw');
  await page.locator('[data-filter="search"]').press('Tab');
  const filtered = await (await page.request.get(`${url}/api/consolidation?env=esp32&search=A0001.raw`)).json();
  expect(filtered.matched).toBeGreaterThan(0);
  await expect(page.locator('#consolidation-table tbody tr')).toHaveCount(filtered.rows.length);
  await expect(page.locator('#consolidation-table')).not.toContainText('pngxcr');
  const after = await (await page.request.get(`${url}/api/consolidation`)).json();
  expect(after.generated_at).toBe(before.generated_at);
  const csv = await page.request.get(`${url}/api/consolidation/download`);
  expect(csv.status()).toBe(200);
  expect(await csv.text()).toContain('execution;model;name_image;quantized;');
  const denied = await page.request.post(`${url}/api/consolidation`, {headers:{Origin:'https://example.com'}, data:{}});
  expect(denied.status()).toBe(403);
  await page.locator('#consolidate').click();
  await expect(page.locator('#consolidate')).toBeEnabled();
  await expect(page.locator('#consolidation-table tbody tr')).toHaveCount(50);
  await page.reload();
  await expect(page.locator('#consolidation-table tbody tr')).toHaveCount(50);
  mkdirSync('test-results', {recursive:true});
  await page.screenshot({path:'test-results/consolidation-desktop.png', fullPage:true});
  await page.locator('#ui-language').click();
  await expect(page.locator('#main h1')).toHaveText('Consolidated analysis');
  await expect(page.locator('#consolidation-table tbody tr')).toHaveCount(50);
  await page.setViewportSize({width:390, height:844});
  await page.waitForTimeout(300); // Allow the responsive sidebar transition to finish.
  await page.screenshot({path:'test-results/consolidation-mobile.png', fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('#main a[href="#analysis-mobilenet"]').click();
  await expect(page.locator('#main h1')).toHaveText('MobileNetV2 · Top-15');
  await expect(page.locator('#consolidation-table th')).toHaveText(['model', 'execution', 'score', 'q', 'name']);
  await expect(page.locator('#consolidation-table tbody tr')).toHaveCount(15);
  const mobile = await (await page.request.get(`${url}/api/mobilenet-consolidation`)).json();
  await page.locator('[data-filter="execution"]').selectOption(mobile.options.execution[0]);
  await expect(page.locator('#consolidation-count')).toHaveText(`15 / ${mobile.total} rows`);
  const generalBefore = await (await page.request.get(`${url}/api/consolidation`)).json();
  await page.locator('#consolidate').click();
  await expect(page.locator('#consolidate')).toBeEnabled();
  expect((await (await page.request.get(`${url}/api/consolidation`)).json()).generated_at).toBe(generalBefore.generated_at);
  const topCsv = await page.request.get(`${url}/api/mobilenet-consolidation/download`);
  expect(await topCsv.text()).toContain('model;execution;score;q;name');
  await page.screenshot({path:'test-results/mobilenet-consolidation-mobile.png', fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('#main a[href="#analysis"]').click();
  await expect(page.locator('[data-filter="model"] option')).toHaveCount(2);
  expect(errors).toEqual([]);
  console.log('Consolidation: filters, pagination, cached reads, CSV, regeneration and origin protection passed.');
} finally { await browser.close(); }
