import { chromium, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';
const url = process.env.EXPLORER_URL || 'http://127.0.0.1:8013';
const browser = await chromium.launch({headless:true, executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
try {
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${url}/#determinism`);
  await expect(page.locator('#det-summary tbody tr')).toHaveCount(6);
  await expect(page.locator('#det-images .det-image')).toHaveCount(20);
  await expect(page.locator('#det-chart .det-image-bar')).toHaveCount(20);
  await expect(page.locator('#det-chart .class-change')).toHaveCount(2);
  await expect(page.locator('#det-images .det-image:visible')).toHaveCount(1);
  await expect(page.locator('#det-aggregate-panel > details')).not.toHaveAttribute('open','');
  await page.locator('#det-chart button').filter({hasText:'a0969.raw'}).click();
  await expect(page.locator('#det-images .det-image:visible h3')).toContainText('a0969.raw');
  await expect(page.locator('#det-images .det-image:visible .det-explanation')).toContainText('classe predita mudou');
  await page.locator('#det-unit').selectOption('scores');
  await page.locator('#det-measure').selectOption('mean');
  await expect(page.locator('#det-magnitudes > details')).toHaveCount(6);
  await expect(page.locator('#det-images .det-image:visible')).toContainText('P99');
  await expect(page.locator('#det-images .det-image:visible')).toContainText('Troca de classe');
  await page.locator('#det-images .det-image:visible details summary').click();
  await expect(page.locator('#det-images .det-image:visible .det-values').first()).toBeVisible();
  await page.locator('[data-det="env"]').selectOption('desktop');
  await expect(page.locator('#det-count')).toHaveText('0 imagens neste filtro');
  await page.locator('[data-det="status"]').selectOption('equal');
  await page.locator('[data-det="search"]').fill('a0002.raw');
  await page.locator('[data-det="search"]').press('Tab');
  await expect(page.locator('#det-images .det-image')).toHaveCount(1);
  const before = await (await page.request.get(`${url}/api/consolidation`)).json();
  await page.locator('#det-generate').click();
  await expect(page.locator('#det-generate')).toBeEnabled({timeout:60000});
  await expect(page.locator('#det-images .det-image')).toHaveCount(1);
  expect((await (await page.request.get(`${url}/api/consolidation`)).json()).generated_at).not.toBe(before.generated_at);
  expect((await page.request.get(`${url}/api/analyses/determinism/download`)).status()).toBe(200);
  expect((await page.request.post(`${url}/api/analyses/determinism`, {headers:{Origin:'https://example.com'}, data:{}})).status()).toBe(403);
  mkdirSync('test-results',{recursive:true});
  await page.locator('[data-det="search"]').fill('');
  await page.locator('[data-det="search"]').press('Tab');
  await page.locator('[data-det="env"]').selectOption('esp32');
  await page.locator('[data-det="status"]').selectOption('different');
  await page.locator('#det-unit').selectOption('quantized');
  await page.locator('#det-measure').selectOption('maximum');
  await expect(page.locator('#det-chart .det-image-bar')).toHaveCount(20);
  await page.screenshot({path:'test-results/determinism-desktop.png',fullPage:true});
  await page.locator('#ui-language').click();
  await expect(page.locator('#main h1')).toHaveText('Within-environment determinism');
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(300);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/determinism-mobile.png',fullPage:true});
  expect(errors).toEqual([]);
  console.log('Determinism UI passed.');
} finally {await browser.close();}
