import { chromium, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';
const url = process.env.EXPLORER_URL || 'http://127.0.0.1:8014';
const browser = await chromium.launch({headless:true, executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
try {
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];
  page.on('pageerror', error=>errors.push(error.message));
  await page.goto(`${url}/#esp32-consensus`);
  await expect(page.locator('#main h1')).toHaveText('Relatórios representativos · ESP32');
  await expect(page.locator('#rep-groups tbody tr')).toHaveCount(2);
  await expect(page.locator('#rep-images .rep-image')).toHaveCount(50);
  await page.locator('#rep-group').selectOption('drowsiness/wasm');
  await page.locator('#rep-status').selectOption('mode');
  await expect(page.locator('#rep-images .rep-image')).toHaveCount(20);
  await page.locator('#rep-search').fill('a0969');
  await page.locator('#rep-search').press('Tab');
  await expect(page.locator('#rep-images .rep-image')).toHaveCount(1);
  await page.locator('.rep-image summary').click();
  await expect(page.locator('.rep-image table tbody tr')).toHaveCount(2);
  const selected=await (await page.request.get(`${url}/api/analyses/esp32-consensus?group=drowsiness/wasm&search=a0969`)).json();
  expect(selected.images[0].votes).toBeGreaterThan(1);
  const download=await page.request.get(`${url}/api/analyses/esp32-consensus/download?group=drowsiness/wasm`);
  expect(download.status()).toBe(200);
  expect((await download.text()).split('\n').length).toBeGreaterThan(2000);
  const before=await (await page.request.get(`${url}/api/consolidation`)).json();
  await page.locator('#rep-generate').click();
  await expect(page.locator('#rep-generate')).toBeEnabled({timeout:30000});
  await expect(page.locator('#rep-images .rep-image')).toHaveCount(1);
  const after=await (await page.request.get(`${url}/api/consolidation?env=esp32`)).json();
  expect(after.generated_at).not.toBe(before.generated_at);
  expect(after.matched).toBe(4000);
  expect(new Set(after.rows.map(r=>r.execution)).size).toBe(1);
  expect(after.options.execution.length).toBe(10);
  expect(after.rows.every(r=>r.source_file.startsWith('analysis/esp32_consensus/'))).toBe(true);
  expect((await page.request.post(`${url}/api/analyses/esp32-consensus`,{headers:{Origin:'https://example.com'},data:{}})).status()).toBe(403);
  mkdirSync('test-results',{recursive:true});
  await page.screenshot({path:'test-results/representative-desktop.png',fullPage:true});
  await page.locator('#ui-language').click();
  await expect(page.locator('#main h1')).toHaveText('Representative reports · ESP32');
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(300); // Complete the responsive sidebar transition before capture.
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/representative-mobile.png',fullPage:true});
  await page.locator('#main a[href="#analysis"]').click();
  await expect(page.locator('#main')).toContainText('ESP32 uses one representative report');
  expect(errors).toEqual([]);
  console.log('Representative ESP32 UI passed.');
} finally {await browser.close();}
